# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Anabada Board' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ImageSlideshow'

  pod 'ImageSlideshow', '~> 1.9.0'

  # Pods for Anabada Board

end
